---
architecture: get_convnext

dataset:
 train:
  - /eos/user/a/adpol/suep/SUEPML-Trial-0.h5
  - /eos/user/a/adpol/suep/SUEPML-Trial-1.h5
  - /eos/user/a/adpol/suep/SUEPML-Trial-2.h5
  - /eos/user/a/adpol/suep/SUEPML-Trial-3.h5
 validation:
  - /eos/user/a/adpol/suep/SUEPML-Trial-0.h5
  - /eos/user/a/adpol/suep/SUEPML-Trial-1.h5
  - /eos/user/a/adpol/suep/SUEPML-Trial-2.h5
  - /eos/user/a/adpol/suep/SUEPML-Trial-3.h5
 test: /path/to/test
  - /eos/user/a/adpol/suep/SUEPML-Trial-0.h5
 in_dim:
  - 1
  - 280
  - 360

training_pref:
 batch_size_train: 20
 batch_size_validation: 20
 boosted: False
 learning_rate: 0.01
 max_epochs: 20
 patience: 50
 weight_decay: 0.0005
 workers: 0

evaluation_pref:
 batch_size: 100
 workers: 0
