---
architecture: LeNet5

dataset:
 train:
  - /scratch/gpfs/ap6964/suepml/Mini-SUEPML-Train-0.h5
  - /scratch/gpfs/ap6964/suepml/Mini-SUEPML-Train-1.h5
  - /scratch/gpfs/ap6964/suepml/Mini-SUEPML-Train-2.h5
  - /scratch/gpfs/ap6964/suepml/Mini-SUEPML-Train-3.h5
 validation:
  - /scratch/gpfs/ap6964/suepml/Mini-SUEPML-Val-0.h5
  - /scratch/gpfs/ap6964/suepml/Mini-SUEPML-Val-1.h5
  - /scratch/gpfs/ap6964/suepml/Mini-SUEPML-Val-2.h5
  - /scratch/gpfs/ap6964/suepml/Mini-SUEPML-Val-3.h5
 test:
  - /scratch/gpfs/ap6964/suepml/Mini-SUEPML-Test.h5
 in_dim:
  - 14
  - 18
 boosted: True

training_pref:
 batch_size_train: 200
 batch_size_validation: 200
 learning_rate: 0.01
 max_epochs: 100
 patience: 20
 weight_decay: 0.0005
 workers: 0

evaluation_pref:
 batch_size: 200
 workers: 0
