---
architecture: get_resnet18

dataset:
 train:
  - /scratch/gpfs/ap6964/suepml/SUEPML-Train-0.h5
  - /scratch/gpfs/ap6964/suepml/SUEPML-Train-1.h5
  - /scratch/gpfs/ap6964/suepml/SUEPML-Train-2.h5
  - /scratch/gpfs/ap6964/suepml/SUEPML-Train-3.h5
 validation:
  - /scratch/gpfs/ap6964/suepml/SUEPML-Val-0.h5
  - /scratch/gpfs/ap6964/suepml/SUEPML-Val-1.h5
  - /scratch/gpfs/ap6964/suepml/SUEPML-Val-2.h5
  - /scratch/gpfs/ap6964/suepml/SUEPML-Val-3.h5
 test:
  - /scratch/gpfs/ap6964/suepml/SUEPML-Test.h5
 in_dim:
  - 280
  - 360
 boosted: True

training_pref:
 batch_size_train: 100
 batch_size_validation: 100
 learning_rate: 0.01
 max_epochs: 50
 patience: 20
 weight_decay: 0.0005
 workers: 0

evaluation_pref:
 batch_size: 100
 workers: 0
